### ISSUE TITLE
issue with importing events

### ISSUE THREAD

**Issue by rschmaelzle** [xdf-modules/xdf-EEGLAB#1]
Hi, first of all thanks for supporting this great module. I've had good results with all kinds of synchronization, but have now run into a problem:
I am using the LSLRecorder to record 3 streams, two muse-eeg systems and one presentation-marker stream. Everything works smoothly, but when I import the streams into eeglab, all events have the exact same timing (in some cases even negative). The eeg looks ok though. 
I've tried using multiple plugins, matlab versions, and I also tried to replace the presentation stream with a keyboard strokes (from the lsl-keyboard app). I have a feeling that this might have to do with the weird sampling rate that muse uses (256hz). 
Does anyone have an idea?
Best ralf

Heres the xdf file...
https://drive.google.com/open?id=1ulPCigvmUfPxE3hInh7KFylFLSQZ44Id

**Comment by cbrnr** [comment]
After syncing, the EEG data starts at time 1559765254.5453062, whereas the marker stream starts at 93273.40176216. This might be the reason why you don't see events (or even negative events, because if you subtract 1559765254.5453062 from the marker times you get negative values). I'm not sure why this happens though...

**Comment by rschmaelzle** [comment]
Hi, after looking more deeply into this I noted that  [over at the LSL repository](https://github.com/sccn/labstreaminglayer/issues/13#issuecomment-499276066) a related issue had been posted. This turned out to deliver a solution (the issue was that the app i used to connect the eegs used a wrong time format - changing that solved it.). Thanks for your help! I am closing it. best r
